export const mock = [
    {
        shortId: 'djYD8BgY',
        body: 'Just tesst',
        categorySlug: 'working',
        numberOfAndroidViews: 0,
        numberOfIosViews: 0,
        numberOfViews: 0,
        tags:
            '[{"id": 1, "slug": "north-america", "type": "location", "nameEn": "north america", "nameVi": "bắc mỹ", "parent": null, "createdOn": "2019-07-24T23:01:04.000Z", "updatedOn": "2019-09-18T15:53:14.000Z", "categorySlug": "working", "numberOfQuestions": 0}]',
        title: 'Test haha',
        numberOfAnswers: 1,
        numberOfVotes: 2,
        hasAcceptedAnswer: false,
        expectPeopleAnswer: null,
        slug: 'test-haha',
        createdBy: 7,
        updatedBy: null,
        id: 18,
        createdOn: '2019-10-03T06:46:29.000Z',
        updatedOn: '2019-10-07T19:53:26.000Z',
        askedBy: {
            avatar:
                'https://cdn0.iconfinder.com/data/icons/user-pictures/100/malecostume-512.png',
            firstName: 'sang',
            lastName: 'huynh',
            numberOfQuestions: 1,
            numberOfAnswers: 1,
            numberOfBestAnswers: 0,
            points: 20,
            level: 'beginner',
            id: 7
        },
        category: { slug: 'working', nameEn: 'working', nameVi: 'công việc' }
    },
    {
        shortId: 'JfW99xxt',
        body: 'à à ấ faf à a',
        categorySlug: 'working',
        numberOfAndroidViews: 0,
        numberOfIosViews: 0,
        numberOfViews: 0,
        tags:
            '[{"id": 5, "slug": "the-united-states", "type": "location", "nameEn": "the united states", "nameVi": "Mỹ", "parent": null, "createdOn": "2019-07-24T23:01:04.000Z", "updatedOn": "2019-09-18T15:54:37.000Z", "categorySlug": "working", "numberOfQuestions": 0}]',
        title: 'sf ấ sà átest ấ sa s',
        numberOfAnswers: 0,
        numberOfVotes: 2,
        hasAcceptedAnswer: false,
        expectPeopleAnswer: null,
        slug: 'sf--s-test--sa-s',
        createdBy: 5,
        updatedBy: null,
        id: 17,
        createdOn: '2019-09-29T14:57:24.000Z',
        updatedOn: '2019-10-06T15:53:26.000Z',
        askedBy: {
            avatar:
                'https://cdn0.iconfinder.com/data/icons/user-pictures/100/malecostume-512.png',
            firstName: 'vbnmvbm',
            lastName: 'test',
            numberOfQuestions: 6,
            numberOfAnswers: 2,
            numberOfBestAnswers: 0,
            points: 40,
            level: 'beginner',
            id: 5
        },
        category: { slug: 'working', nameEn: 'working', nameVi: 'công việc' }
    },
    {
        shortId: 'mX7l0w4h',
        body: 'how to ...?',
        categorySlug: 'immigration',
        numberOfAndroidViews: 0,
        numberOfIosViews: 0,
        numberOfViews: 0,
        tags:
            '[{"id": 91, "slug": "north-america", "type": "location", "nameEn": "north america", "nameVi": "bc m", "parent": null, "createdOn": "2019-07-24T23:01:04.000Z", "updatedOn": "2019-09-23T12:31:32.000Z", "categorySlug": "immigration", "numberOfQuestions": 1}]',
        title: 'test 1',
        numberOfAnswers: 1,
        numberOfVotes: 1,
        hasAcceptedAnswer: false,
        expectPeopleAnswer: null,
        slug: 'test-1',
        createdBy: 3,
        updatedBy: null,
        id: 16,
        createdOn: '2019-09-23T13:24:55.000Z',
        updatedOn: '2019-10-07T18:29:53.000Z',
        askedBy: {
            avatar:
                'https://cdn0.iconfinder.com/data/icons/user-pictures/100/malecostume-512.png',
            firstName: 'Thanh',
            lastName: 'Nguyen',
            numberOfQuestions: 4,
            numberOfAnswers: 0,
            numberOfBestAnswers: 0,
            points: 40,
            level: 'beginner',
            id: 3
        },
        category: {
            slug: 'immigration',
            nameEn: 'immigration',
            nameVi: 'nhập cư'
        }
    },
    {
        shortId: '3ux4kT8L',
        body: 'fewfdsa',
        categorySlug: 'immigration',
        numberOfAndroidViews: 0,
        numberOfIosViews: 0,
        numberOfViews: 0,
        tags:
            '[{"id": 91, "slug": "north-america", "type": "location", "nameEn": "north america", "nameVi": "bc m", "parent": null, "createdOn": "2019-07-24T23:01:04.000Z", "updatedOn": "2019-07-24T23:01:04.000Z", "categorySlug": "immigration", "numberOfQuestions": 0}]',
        title: 'fdsfdsf',
        numberOfAnswers: 0,
        numberOfVotes: 1,
        hasAcceptedAnswer: false,
        expectPeopleAnswer: null,
        slug: 'fdsfdsf',
        createdBy: 3,
        updatedBy: null,
        id: 15,
        createdOn: '2019-09-23T12:31:32.000Z',
        updatedOn: '2019-09-29T14:52:33.000Z',
        askedBy: {
            avatar:
                'https://cdn0.iconfinder.com/data/icons/user-pictures/100/malecostume-512.png',
            firstName: 'Thanh',
            lastName: 'Nguyen',
            numberOfQuestions: 4,
            numberOfAnswers: 0,
            numberOfBestAnswers: 0,
            points: 40,
            level: 'beginner',
            id: 3
        },
        category: {
            slug: 'immigration',
            nameEn: 'immigration',
            nameVi: 'nhập cư'
        }
    },
    {
        shortId: 'L6gIMvP3',
        body: 'sdafasdf asf asfasf asdf ',
        categorySlug: 'working',
        numberOfAndroidViews: 0,
        numberOfIosViews: 0,
        numberOfViews: 0,
        tags:
            '[{"id": 1, "slug": "north-america", "type": "location", "nameEn": "north america", "nameVi": "bắc mỹ", "parent": null, "createdOn": "2019-07-24T23:01:04.000Z", "updatedOn": "2019-09-18T15:53:14.000Z", "categorySlug": "working", "numberOfQuestions": 0}]',
        title: 'Test thoi nhe',
        numberOfAnswers: 1,
        numberOfVotes: 0,
        hasAcceptedAnswer: false,
        expectPeopleAnswer: null,
        slug: 'test-thoi-nhe',
        createdBy: 5,
        updatedBy: null,
        id: 14,
        createdOn: '2019-09-20T15:51:20.000Z',
        updatedOn: '2019-09-22T08:53:28.000Z',
        askedBy: {
            avatar:
                'https://cdn0.iconfinder.com/data/icons/user-pictures/100/malecostume-512.png',
            firstName: 'vbnmvbm',
            lastName: 'test',
            numberOfQuestions: 6,
            numberOfAnswers: 2,
            numberOfBestAnswers: 0,
            points: 40,
            level: 'beginner',
            id: 5
        },
        category: { slug: 'working', nameEn: 'working', nameVi: 'công việc' }
    },
    {
        shortId: 'yUTcRFnN',
        body: 'I want to learn js',
        categorySlug: 'studying',
        numberOfAndroidViews: 0,
        numberOfIosViews: 0,
        numberOfViews: 0,
        tags: '[]',
        title: 'Learn js',
        numberOfAnswers: 0,
        numberOfVotes: 1,
        hasAcceptedAnswer: false,
        expectPeopleAnswer: null,
        slug: 'learn-js',
        createdBy: 3,
        updatedBy: null,
        id: 12,
        createdOn: '2019-09-20T09:15:55.000Z',
        updatedOn: '2019-10-02T19:28:36.000Z',
        askedBy: {
            avatar:
                'https://cdn0.iconfinder.com/data/icons/user-pictures/100/malecostume-512.png',
            firstName: 'Thanh',
            lastName: 'Nguyen',
            numberOfQuestions: 4,
            numberOfAnswers: 0,
            numberOfBestAnswers: 0,
            points: 40,
            level: 'beginner',
            id: 3
        },
        category: { slug: 'studying', nameEn: 'studying', nameVi: 'học tập' }
    },
    {
        shortId: 'EN8ldIfp',
        body: 'I want to learn js',
        categorySlug: 'studying',
        numberOfAndroidViews: 0,
        numberOfIosViews: 0,
        numberOfViews: 0,
        tags: '[]',
        title: 'Question',
        numberOfAnswers: 0,
        numberOfVotes: 1,
        hasAcceptedAnswer: false,
        expectPeopleAnswer: null,
        slug: 'question',
        createdBy: 3,
        updatedBy: null,
        id: 9,
        createdOn: '2019-09-20T09:15:30.000Z',
        updatedOn: '2019-09-29T16:48:05.000Z',
        askedBy: {
            avatar:
                'https://cdn0.iconfinder.com/data/icons/user-pictures/100/malecostume-512.png',
            firstName: 'Thanh',
            lastName: 'Nguyen',
            numberOfQuestions: 4,
            numberOfAnswers: 0,
            numberOfBestAnswers: 0,
            points: 40,
            level: 'beginner',
            id: 3
        },
        category: { slug: 'studying', nameEn: 'studying', nameVi: 'học tập' }
    },
    {
        shortId: 'hdGUY7L8',
        body: 's;nfs f à ìa ihs à á à ',
        categorySlug: 'working',
        numberOfAndroidViews: 0,
        numberOfIosViews: 0,
        numberOfViews: 0,
        tags:
            '[{"id": 14, "slug": "the-united-kingdom", "type": "location", "nameEn": "the united kingdom", "nameVi": "vương quốc anh", "parent": null, "createdOn": "2019-07-24T23:01:04.000Z", "updatedOn": "2019-09-18T15:56:25.000Z", "categorySlug": "working", "numberOfQuestions": 0}, {"id": 4, "slug": "australia", "type": "location", "nameEn": "australia", "nameVi": "úc", "parent": null, "createdOn": "2019-07-24T23:01:04.000Z", "updatedOn": "2019-09-18T15:54:18.000Z", "categorySlug": "working", "numberOfQuestions": 0}]',
        title: 'Test',
        numberOfAnswers: 0,
        numberOfVotes: 0,
        hasAcceptedAnswer: false,
        expectPeopleAnswer: null,
        slug: 'test',
        createdBy: 5,
        updatedBy: null,
        id: 8,
        createdOn: '2019-09-19T22:17:15.000Z',
        updatedOn: '2019-09-19T22:17:15.000Z',
        askedBy: {
            avatar:
                'https://cdn0.iconfinder.com/data/icons/user-pictures/100/malecostume-512.png',
            firstName: 'vbnmvbm',
            lastName: 'test',
            numberOfQuestions: 6,
            numberOfAnswers: 2,
            numberOfBestAnswers: 0,
            points: 40,
            level: 'beginner',
            id: 5
        },
        category: { slug: 'working', nameEn: 'working', nameVi: 'công việc' }
    },
    {
        shortId: 'Cce1bNLa',
        body: 'XCV',
        categorySlug: 'working',
        numberOfAndroidViews: 0,
        numberOfIosViews: 0,
        numberOfViews: 0,
        tags: '[]',
        title: 'XCVX',
        numberOfAnswers: 0,
        numberOfVotes: 1,
        hasAcceptedAnswer: false,
        expectPeopleAnswer: null,
        slug: 'xcvx',
        createdBy: 5,
        updatedBy: null,
        id: 7,
        createdOn: '2019-09-19T22:08:23.000Z',
        updatedOn: '2019-10-05T05:11:33.000Z',
        askedBy: {
            avatar:
                'https://cdn0.iconfinder.com/data/icons/user-pictures/100/malecostume-512.png',
            firstName: 'vbnmvbm',
            lastName: 'test',
            numberOfQuestions: 6,
            numberOfAnswers: 2,
            numberOfBestAnswers: 0,
            points: 40,
            level: 'beginner',
            id: 5
        },
        category: { slug: 'working', nameEn: 'working', nameVi: 'công việc' }
    },
    {
        shortId: 'Y5lRghRY',
        body: 'SDGDSGD',
        categorySlug: 'immigration',
        numberOfAndroidViews: 0,
        numberOfIosViews: 0,
        numberOfViews: 0,
        tags:
            '[{"id": 91, "slug": "north-america", "type": "location", "nameEn": "north america", "nameVi": "bc m", "parent": null, "createdOn": "2019-07-24T23:01:04.000Z", "updatedOn": "2019-07-24T23:01:04.000Z", "categorySlug": "immigration", "numberOfQuestions": 0}]',
        title: 'S',
        numberOfAnswers: 0,
        numberOfVotes: 0,
        hasAcceptedAnswer: false,
        expectPeopleAnswer: null,
        slug: 's',
        createdBy: 5,
        updatedBy: null,
        id: 6,
        createdOn: '2019-09-19T22:04:04.000Z',
        updatedOn: '2019-09-19T22:04:04.000Z',
        askedBy: {
            avatar:
                'https://cdn0.iconfinder.com/data/icons/user-pictures/100/malecostume-512.png',
            firstName: 'vbnmvbm',
            lastName: 'test',
            numberOfQuestions: 6,
            numberOfAnswers: 2,
            numberOfBestAnswers: 0,
            points: 40,
            level: 'beginner',
            id: 5
        },
        category: {
            slug: 'immigration',
            nameEn: 'immigration',
            nameVi: 'nhập cư'
        }
    }
];
