export default {
  common_questions: 'Questions',
  common_answers: 'Answers',
  common_stats: 'Stats',
  common_users: 'Users',
  common_popular: 'Popular',
  common_slidebar: 'Slidebar',
  common_points: 'Points',
  common_previous_step: 'Previous step',
  common_next: 'Next',
  common_bold: 'bold',
  common_and: 'and',
  common_italic: 'italic',
  common_check_out: 'Check out',
  common_title: 'Title',
  common_tags: 'Tags',
  common_for_exemple: 'For example',

  header_home: 'Home',
  header_about_us: 'About Us',
  header_contact_us: 'Contact Us',
  header_blog: 'Blog',
  header_user_profile: 'User Profile',
  header_edit_profile: 'Edit Profile',
  header_best_answers: 'Best Answers',
  header_logout: 'Logout',
  home_ask_a_question: 'Ask a Question',
  home_share_and_grow: "Share & grow the world's knowledge!",
  home_description: `We want to connect the people who have knowledge to the people who need it, to bring
  together people with different perspectives so they can understand each other better,
  and to empower everyone to share their knowledge.`,
  home_create_a_new_account: 'Create A New Account',

  nav_home: 'Home',
  nav_communities: 'Communities',
  nav_questions: 'Question',
  nav_new_question: 'New Questions',
  nav_trending_question: 'Trending Questions',
  nav_must_read_question: 'Must read Questions',
  nav_hot_question: 'Hot Questions',
  nav_tags: 'Tags',
  nav_badges: 'Badges',
  nav_users: 'Users',
  nav_help: 'Help',
  nav_ask_a_question: 'Ask a question',
  nav_best_answers: 'Best Answers',
  nav_top_members: 'Top Members',

  question_tell_us_your_questions: 'Tell us more about your question',
  question_your_description:
    'Your description gives people the information they need to help you answer your question.',
  question_check_out_these_examples:
    'Check out these examples of great question descriptions',
  question_want_more_help: 'Want more help',
  question_review_question: 'Review your question',
  question_let_one_more_look: `Almost there! Let’s give your question one more look. And don’t worry—you can edit your question after it’s posted, too.`,
  question_check_for_typos:
    'Check for typos, slang, and text formatting issues',
  question_for_exemple: 'For example',
  question_format_text: 'Format your text with',
  question_donnot_include_slang: ` Don’t include slang or shorthand: “u can’t bc it's mine”`,
  question_these_tips_for_editing: 'these tips for editing with Markdown',
  question_for_guidance: 'for guidance',
  question_post_your_question: 'Post Your Question',
  question_what_your_programming: `What's your programming question? Be specific.`,
  question_what_languages_technologies:
    'What languages, technologies, and/or frameworks is your question about?',
  question_tags_help_the_right_people:
    'Tags help the right people find and answer your question.',
  question_identify_your_tags: `Identify your tags by completing the sentence, “My question is about…”`,
  question_include_tags_that:
    'Include tags that are crucial to your question only, like europe, us,...',
  question_only_included_in: 'Only included in the proposed scope',
  question_your_title_help:'Your title helps people quickly understand what your question is about so they can answer it.',
  question_imagine_you:`Imagine you’re asking a question to another developer.`,
  question_is_there_an_R : `“Is there an R function for finding the index of an element in a vector?”`,
  question_please_help_with_R : `“Please help with R”`,
  quetion_what_is_your_title : "What’s your question title?",
  question_what_category_of_questions : "What category of questions do you want to ask?",
  question_we_will_help_you:"We'll help you find the best way to get your answer.",
  question_i_have_a_question_about: "I have a question about studying",
  question_i_nedd_help_with:"I need help with a working problem",
  question_i_nedd_to_troubleshoot:"I need to troubleshoot some immigration",
  
};
