export default {

  common_questions:"Questions",
  common_answers:"Answers",
  common_stats: "Stats",
  common_users:"Users",
  common_popular:"Popular",
  common_slidebar:"Slidebar",
  common_points:"Points",
  
  header_home : "Home",
  header_about_us: "About Us",
  header_contact_us: "Contact Us",
  header_blog: "Blog",
  header_user_profile:"User Profile",
  header_edit_profile:"Edit Profile",
  header_best_answers:"Best Answers",
  header_logout:"Logout",
  home_ask_a_question:"Ask a Question",
  home_share_and_grow:"Share & grow the world's knowledge!",
  home_description:`We want to connect the people who have knowledge to the people who need it, to bring
  together people with different perspectives so they can understand each other better,
  and to empower everyone to share their knowledge.`,
  home_create_a_new_account: 'Create A New Account',
  nav_home: 'Home',
  nav_communities: 'Communities',
  nav_questions: 'Question',
  nav_new_question: 'New Questions',
  nav_trending_question: 'Trending Questions',
  nav_must_read_question: 'Must read Questions',
  nav_hot_question: 'Hot Questions',
  nav_tags: 'Tags',
  nav_badges: 'Badges',
  nav_users:'Users',
  nav_help:'Help',
  nav_ask_a_question : "Ask a question",
  nav_best_answers: "Best Answers",
  nav_top_members : "Top Members"
}