export default {
    common_questions: 'Questions',
    common_answer: 'Answer',
    common_answers: 'Answers',
    common_stats: 'Stats',
    common_users: 'Users',
    common_popular: 'Popular',
    common_slidebar: 'Slidebar',
    common_points: 'Points',
    common_previous_step: 'Previous step',
    common_next: 'Next',
    common_bold: 'bold',
    common_and: 'and',
    common_italic: 'italic',
    common_check_out: 'Check out',
    common_title: 'Title',
    common_tags: 'Tags',
    common_for_exemple: 'For example',
    common_voted: 'Voted',
    common_oldest: 'Oldest',
    common_rencent: 'Recent',
    common_view_profile: 'View Profile',
    common_approve: 'Approve',
    common_reply: 'Reply',
    common_share: 'Share',
    common_report: 'Report',
    common_home: 'Home',
    common_asked: 'Asked',
    common_in: 'In',
    common_language: 'Language',
    common_views: 'Views',
    common_followers: 'Followers',
    common_name: 'Name',
    common_badges: 'Badges',
    common_beginner: 'Beginner',
    common_teacher: 'Teacher',
    common_top_members: 'Top members',
    common_login: 'Login',
    common_registre: 'Sign Up',
    common_forgot_password: 'Forgot password',
    common_email: 'Email',
    common_password: 'Password',
    common_mentor: 'mentor',
    common_mentee: 'mentee',
    common_with_us: 'with us',
    common_your_history: 'your story',
    common_company: 'Company',
    common_location: 'Location',
    common_start_date: 'Start date',
    common_end_date: 'End date',
    common_present: 'Present',
    common_description: 'Description',
    common_lastname: 'Last name',
    common_firstname: 'First name',
    common_summary: 'Summary',
    common_nationality: 'Nationality',
    common_date_of_birth: 'Date of birth',
    common_field_of_study: 'Field of study',
    common_from_year: 'From year',
    common_to_year: 'To year',
    common_save: 'Save',
    common_reset: 'Reset',
    common_my_profile: 'My profile',
    common_edit: 'Edit',
    common_general_infos: 'General infos',
    common_all: 'All',
    common_recent: 'Recent',
    common_show: 'Show',
    common_hide: 'Hide',
    common_trending_tags: 'Trending tags',
    common_education: 'Education',
    common_experience: 'Experience',
    common_no_result: 'No result',
    common_come_back: 'Come back',
    common_userName: 'User name',
    common_invalid_username: 'Invalid user name!',
    common_popular_question: 'Popular question',
    common_see_all: 'See all',
    common_ask_now: 'Ask a question now?',
    common_ask: 'Ask',
    common_ask_a_question: 'Ask a question',
    common_about_us: 'About Us',
    common_contact_us: 'Contact Us',
    common_policy: 'Policy',
    common_follow_us: 'Follow us',
    common_sort_by: 'Sort by',
    common_information: 'Information',
    common_points_scale: 'Points scale',
    common_category: 'Category',
    common_review: 'Review',
    common_close: 'Close',
    common_how_does_it_work: 'How does it work',
    common_step: 'Step',
    common_more_detail: 'More detail',
    common_ask_to: 'Ask to',
    common_or: 'Or',
    common_private: 'Private',
    common_public: 'Public',
    common_user: 'User',
    common_ok: 'Ok',
    common_cancel: 'Cancel',
    common_logged_in: 'Logged in!',
    common_contact: 'Contact',
    common_agree: 'Agree',
    common_example: 'Example',
    common_status: 'Status',
    common_coming_soon:'coming soon',
    common_posts: 'Posts',
    common_add_post:'Add new post',
    common_main_character:'Main character',
    common_user_name: 'User name',
    common_cover_image: 'Cover Image',
    common_resume: 'Resume',
    common_submit: 'Submit',
    common_like: 'Like',
    common_unlike: 'Unlike',

    pagination_previous: 'Previous',
    pagination_next: 'Next',

    authentification_enter_your_email:
        'Enter your email address to recover your password',
    authentification_reset_password: 'Reset password',
    authentification_back_to_login: 'Back to login',
    authentification_first_name: 'First Name',
    authentification_last_name: 'Last Name',
    authentification_confirm_password: 'Confirm Password',
    authentification_create_account: 'Create Account',
    authentification_remember_me: 'Remember Me',
    authentification_sign_up: 'Sign up',
    authentification_forgot_your_password: 'Forgot your password',
    authentification_donot_have_account: `Don't have an account?`,
    authentification_this_page_need_to_authenticate:
        'This page need to authentificate to continue',
    authentification_check_your_email:
        'Check your email to complete the registration!',
    authentication_i_agree: 'I agree to ',
    authentication_terms_and_condition: 'Terms and Conditions ',
    authentication_of_VCNC: 'of VCNC',
    authentication_please_agree_with_our_terms:
        'Please agree with our terms and condition',
    authentification_: '',

    header_home: 'Home',
    header_blog: 'Blog',
    header_user_profile: 'User Profile',
    header_edit_profile: 'Edit Profile',
    header_best_answers: 'Best Answers',
    header_logout: 'Logout',

    home_ask_a_question: 'Ask a Question',
    home_share_and_grow: "Share & grow the world's knowledge!",
    home_description: `We want to connect the people who have knowledge to the people who need it, to bring
  together people with different perspectives so they can understand each other better,
  and to empower everyone to share their knowledge.`,
    home_create_a_new_account: 'Create A New Account',

    nav_home: 'Home',
    nav_communities: 'Communities',
    nav_questions: 'Questions',
    nav_new_question: 'New Questions',
    nav_trending_question: 'Trending Questions',
    nav_must_read_question: 'Must read Questions',
    nav_hot_question: 'Hot Questions',
    nav_tags: 'Tags',
    nav_badges: 'Badges',
    nav_users: 'Users',
    nav_help: 'Help',
    nav_ask_a_question: 'Ask a question',
    nav_best_answers: 'Best Answers',
    nav_top_members: 'Top Members',

    question_tell_us_your_questions: 'Tell us more about your question',
    question_your_description:
        'Your description gives people the information they need to help you answer your question.',
    question_check_out_these_examples:
        'Check out these examples of great question descriptions',
    question_want_more_help: 'Want more help',
    question_review_question: 'Review your question',
    question_let_one_more_look: `Almost there! Let's take one more look before submitting your question.`,
    question_for_exemple: 'For example',
    question_format_text: 'Format your text with',
    question_donnot_include_slang: ` Don’t include slang or shorthand: “u can’t bc it's mine”`,
    question_these_tips_for_editing: 'these tips for editing with Markdown',
    question_for_guidance: 'for guidance',
    question_post_your_question: 'Submit Your Question',
    question_what_your_programming: `What's your programming question? Be specific.`,
    question_tags_help_the_right_people:
        'To help readers navigate your question easily, you can add some tags related to your question (optional).',
    question_your_title_help:
        'Your title helps people quickly understand what your question is about so they can answer it.',
    question_imagine_you: `Imagine you’re asking a question to another developer.`,
    question_is_there_an_R: `“Is there an R function for finding the index of an element in a vector?”`,
    question_please_help_with_R: `“Please help with R”`,
    quetion_what_is_your_title: 'What’s your question title?',
    question_what_category_of_questions:
        'Please choose a category for your question:',
    question_i_have_a_question_about: 'I have a question about studying',
    question_i_nedd_help_with: 'I need help with a working problem',
    question_i_nedd_to_troubleshoot: 'I need to troubleshoot some immigration',
    question_answer_min_20: 'Please leave an answer at least 20 characters',
    question_search_question: 'Search question',
    question_hit_enter_to_search: 'Hit enter to search',
    question_resolved: 'Resolved',
    question_set_mode: 'Do you want to publish your question?',
    question_set_mode_des: 'If you choose to publish, everyone can give you an answer. If you choose not to, your question will be visible only to people you want to get answer from.',
    question_support_list: 'Who do you want to get answer from? (optional)',
    question_support_list_des:
        'We will send a notification to these people.',
    question_support_list_des_sup_empty: `You can choose up to 2 people.`,
    question_support_list_require:
        'Your question is private, please choose at least one person to answer your question',

    question_leaved_an_answer: 'Thanks for submitting your answer',
    question_approved_this_answer: 'Approved this answer',
    question_created_a_question: 'Created a question',

    question_tags_developer_life:'How is the work life balance of a Google software developer?',
    question_tags_example:'Google, work life balance',

    post_more_from_VCNC: 'More from VCNC',
    
    answer_best_answers: 'Best Answers',
    answer_leave_answer: 'Leave an answer',

    share_on_facebook: 'Share on Facebook',
    share_on_twitter: 'Share on Twitter',
    share_on_linkedIn: 'Share on LinkedIn',

    badges_point_system: 'Points System',
    badges_beside_gaining_reputation:
        'At VCNC, we value your contribution no matter how big or small. You will get a new badge every time you reach a new level.',
    badges_shown: 'Badges will appear besides your name every time you ask a question or leave an answer.',
    badges_points_for_a_new: 'awarded to every new user of the community.',
    badges_choosing_the_best: 'Choosing the best answer for a question.',
    badges_add_an_answer: 'awarded for any answer.',
    badges_voting_a_question: 'Voting a question in the community.',
    badges_following_a_user: 'Following a user in the community.',
    badges_voting_an_answer: 'Voting an answer in the community.',
    badges_badges_system: 'Badges System',
    badges_pundit: 'Pundit',
    badges_explainer: 'Explainer',
    badges_enlightened: 'Enlightened',
    badges_you_must_have: 'You must have a total score of',
    badges_in_at_least: 'in at least',
    badges_non_community_wiki:
        'non-community wiki answers to achieve this badge. Highest scoring answer that outscored an accepted answer with score of more than',
    badges_beginner: 'Beginner',
    badges_professional: 'Professional {{level}}',
    badges_intermediate: 'Intermediate {{level}}',
    badges_expert: 'Expert',

    badges_profile_compeleted: 'awarded if you complete your profile.',
    badges_answer_approved: 'awarded for any approved answer.',
    badges_ask_a_question: 'awarded for any question.',
    badges_up_vote_on_question_or_answer:
        'awarded for every upvote for your question or answer.',
    badges_down_vote_on_question_or_answer:
        'negative point for every down vote for your question or answer.',
    badges_share_question_or_answer: 'bonus point for sharing a question or answer on social media (facebook/twitter/linkedin).',
    badges_login: 'bonus point for daily check-in.',
    badges_points_limit: 'It has limit of {{points}} points per day',

    mainpage_recent_question: 'Recent Questions',
    mainpage_most_answerd: 'Most Answered',
    mainpage_most_visited: 'Most Visited',
    mainpage_most_voted: 'Most Voted',
    mainpage_danang_vietnam: 'Da nang, Viet Nam',
    mainpage_load_more_questions: 'Load More Questions',

    questions_no_answers: 'No Answers',
    questions_my_questions: 'My questions',
    questions_ask_me: 'Ask me',

    question_public: 'Public question',
    question_private: 'Private question',
    question_created_title_limit: 'Title must have minimum 20 characters',
    question_created_body_limit: 'Description must have minimum 20 characters',

    login_thank_to_login_to_continue: 'Thank to login to continue',

    contact_us_hello: 'We are here to listen to you!',
    contact_us_if_you_want_to_share:
        'If you want to share your story on VCNC blog or need other support, please email to ',
    contact_us_reply_soon: ' We will contact you as soon as possible.',
    contact_us_get_live_support: 'Get live support',
    contact_us_sincerely: 'Sincerely,',

    about_us_VCNC: 'Vietnamese Counselling and Connecting',
    about_us_sologan: 'Get people connected',
    about_us_our_story: 'Our story',
    about_us_story: `We are a group of passionate Vietnamese students with an ambition to create the biggest and coolest professionals network for talented people to get advice and support for their career.`,
    about_us_what_we_do: 'What we do',
    about_us_do:
        'We build a platform where people can ask questions and receive trustworthy answers from professionals all over the world using advanced matching algorithms. Besides that, we offer mentorship packages that our mentees can get connected directly with influential people. Our network will help you get access to the support and connections you need in your way to achieve your biggest dreams.',
    about_us_our_team: 'Meet our team',
    about_us_nguyet_role: 'Co-founder - CEO',
    about_us_nguyet_experience:
        'PhD student at University of Southern California',
    about_us_phuc_role: 'Co-founder - COO',
    about_us_phuc_experience: 'Full-stack developer at Kumullus',
    about_us_sang_role: 'Co-founder - CTO',
    about_us_sang_experience: 'Senior developer at Peddler',
    about_us_toan_role: 'Chief Scientist',
    about_us_toan_experience: 'Senior Research Engineer at Berkeley Lab',
    about_us_nguyen_role: 'Chief Marketing Officer',
    about_us_nguyen_experience: 'Marketing Executive at Advosights',

    forgot_password_please_verify_your_email:
        'Please verify your email to reset password',
    authentification_enter_new_password: 'Enter your new password',
    authentification_new_password: 'New password',
    authentification_confirm_new_password: 'Confirm new password',
    authentification_invalid_comfirm_password: 'Invalid confirm password',
    authentification_your_password_has_been_reset:
        'Your password has been reseted',
    authentication_please_enter_email_and_password:
        'Please enter your email and password to continue',

    form_require_all_values: 'Please enter all values required.',
    form_your_job: 'Your job',
    form_current_role: 'I am currently working in this role',
    form_ex_work_manager: 'Ex: Manager',
    form_your_school: 'Your School',

    my_profile_you_come_from: 'You comme from',
    my_profile_choose_one_country: 'Choose one country',
    my_profile_user_info_updated: 'Your profile has been updated!',
    my_profile_change_password: 'Change password',
    my_profile_old_password: 'Old password',
    my_profile_new_password: 'New password',
    my_profile_passwords_not_identique: 'Your new passwords are not the same',
    my_profile_change_password_success: 'Your password is changed!',
    my_profile_confirm_new_password: 'Confirm new password',
    my_profile_please_complete_all_fields: 'Please complete all fields',
    my_profile_passwords_contrain:
        'Your password must have at least 8 character, 1 uppercase letter, 1 lowercase letter, 1 digit ',

    user_info_question_asked: 'Question asked',
    user_info_amswers_related: 'Answers related',
    user_info_added_an_answer: 'Added an answer on',
    user_info_experience_created: 'Experience created!',
    user_info_experience_updated: 'Experience updated!',
    user_info_education_created: 'Education created!',
    user_info_education_updated: 'Education updated!',

    home_ask_verified_professionals:
        'Ask verified professionals for career advices, interview training, resume review and company insights...',
    home_want_to_get: 'Want to get paid for sharing your knowledge?',
    home_find_out_how: 'Find out how we work',
    home_do_you_have_a_question: 'Do you have a question?',

    workspace_if_you_are_asking: 'If you are asking',
    workspace_post_a_question: 'Post a question',
    workspace_choose_professionals: 'Choose professionals to get matched',
    workspace_receive_answer_from: 'Receive answer from professionals',
    workspace_rate_your_experience: 'Rate your experience and get bonus',
    workspace_if_you_are_answering: 'If you are answering',
    workspace_get_notification:
        'Get notification if you are requested to answer a question',
    workspace_answer_the_assigned: 'Answer the assigned question in 24h',
    workspace_get_paid: 'Get bonus after submitting your answer',
    
    workspace_our_support: 'Our support',
    workspace_how_to_ask:'How to ask a question?',
    workspace_how_to_find_mentor:'How to find a mentor?',
    workspace_how_to_get_customer_support: 'How to get customer support?',

    footer_all_right_reserved: 'All rights reserved © 2020',

    answer_added_an_answer_on: 'Added on',

    infos_what_does_VCNC_do: 'What does VCNC do?',
    infos_what_does_VCNC_do_description:
        'We are here to connect you with professionals around the world that can provide you the best answers for your inquiry as well as the support you need for your career.',
    infos_get_started: `Don't know how to get started? It's surprisingly simple!`,
    infos_new_step1:
        'Register an account with VCNC. You can register with your email or just connect with your existing google/facebook account.',
    infos_new_step2:
        'Now you are ready to go. Go to vcnc.app and ask any question to get connected to our professionals network!',
    infos_new_step3: `Don't forget to come back to get the answer. You will get notifications when someone answers your question. If you are satisfied with an answer, don't forget to APPROVE that answer so your friend can get the credit!`,
    infos_conclusion: 'Needless to say, we are happy that you are here!',

    cookie_banner_info1:
        'To make VCNC work, we log user data. By using VCNC, you agree to our ',
    cookie_banner_info2: ', including '
};
