export default {
    common_questions: 'Câu hỏi',
    common_answer: 'Câu trả lời',
    common_answers: 'Câu trả lời',
    common_stats: 'Số liệu',
    common_users: 'Người dùng',
    common_popular: 'Độ phổ biến',
    common_slidebar: 'Thanh trượt',
    common_points: 'Điểm',
    common_previous_step: 'Quay lại',
    common_next: 'Tiếp theo',
    common_bold: 'đậm',
    common_and: 'và',
    common_italic: 'nghiêng',
    common_check_out: 'Thanh toán',
    common_title: 'Tiêu đề',
    common_tags: 'Tags',
    common_for_exemple: 'Ví dụ',
    common_voted: 'Thích',
    common_oldest: 'Cũ nhất',
    common_rencent: 'Mới nhất',
    common_view_profile: 'Xem trang cá nhân',
    common_approve: 'Đồng ý',
    common_reply: 'Trả lời',
    common_share: 'Chia sẻ',
    common_report: 'Báo cáo',
    common_home: 'Trang chủ',
    common_asked: 'Đã hỏi',
    common_in: 'Trong',
    common_language: 'Ngôn ngữ',
    common_views: 'Lượt xem',
    common_followers: 'Lượt theo dõi',
    common_name: 'Tên',
    common_badges: 'Huy hiệu',
    common_beginner: 'Người bắt đầu',
    common_teacher: 'Người hướng dẫn',
    common_top_members: 'Thành viên tích cực',
    common_login: 'Đăng nhập',
    common_registre: 'Đăng ký',
    common_forgot_password: 'Quên mật khẩu',
    common_email: 'Email',
    common_password: 'Mật khẩu',
    common_mentor: 'mentor',
    common_mentee: 'mentee',
    common_with_us: 'với chúng tôi',
    common_your_history: 'câu chuyện của mình',
    common_company: 'Công ty',
    common_location: 'Địa chỉ',
    common_start_date: 'Từ ngày',
    common_end_date: 'Đến ngày',
    common_present: 'Đến nay',
    common_description: 'Mô tả',
    common_lastname: 'Họ',
    common_firstname: 'Tên',
    common_summary: 'Giới thiệu',
    common_nationality: 'Quốc tịch',
    common_date_of_birth: 'Ngày sinh',
    common_field_of_study: 'Ngành học',
    common_from_year: 'Từ năm',
    common_to_year: 'Đến năm',
    common_save: 'Lưu',
    common_reset: 'Đặt lại',
    common_my_profile: 'Hồ sơ cá nhân',
    common_edit: 'Chỉnh sửa',
    common_general_infos: 'Thông tin chung',
    common_all: 'Tất cả',
    common_recent: 'Gần đây',
    common_show: 'Hiện',
    common_hide: 'Ẩn',
    common_trending_tags: 'Tags phổ  biến',
    common_education: 'Học vấn',
    common_experience: 'Kinh nghiệm',
    common_no_result: 'Không tìm thấy kết quả',
    common_come_back: 'Quay lại',
    common_userName: 'Tên người dùng',
    common_invalid_username: 'Tên người dùng không hợp lệ!',
    common_popular_question: 'Câu hỏi phổ biến',
    common_see_all: 'Xem tất cả',
    common_ask_now: 'Đặt ngay một câu hỏi?',
    common_ask: 'Đặt câu hỏi',
    common_about_us: 'Giới thiệu',
    common_contact_us: 'Liên hệ',
    common_policy: 'Policy',
    common_follow_us: 'Theo dõi chúng tôi',
    common_sort_by: 'Sắp xếp',
    common_information: 'Thông tin',
    common_point_scale: 'Thang điểm',
    common_category: 'Category',
    common_review: 'Xem trước',
    common_close: 'Đóng',
    common_how_does_it_work: 'Hoạt động như thế nào',
    common_step: 'Bước',
    common_more_detail: 'Chi tiết',
    common_ask_to: 'Hỏi đến',
    common_or: 'Hoặc',
    common_private: 'Riêng tư',
    common_public: 'Công khai',
    common_user: 'Người dùng',
    common_ok: 'Đồng ý',
    common_cancel: 'Huỷ',
    common_logged_in: 'Đăng nhập thành công!',

    pagination_previous: 'Trước',
    pagination_next: 'Sau',

    authentification_enter_your_email: 'Nhập địa chỉ email của bạn',
    authentification_reset_password: 'Đặt lại mật khẩu',
    authentification_back_to_login: 'Trở về đăng nhập',
    authentification_first_name: 'Tên',
    authentification_last_name: 'Họ',
    authentification_confirm_password: 'Xác nhận mật khẩu',
    authentification_create_account: 'Tạo tài khoản',
    authentification_remember_me: 'Nhớ thông tin đăng nhập',
    authentification_sign_up: 'Đăng ký',
    authentification_forgot_your_password: 'Quên mật khẩu',
    authentification_donot_have_account: `Bạn chưa có tài khoản`,
    authentification_this_page_need_to_authenticate:
        'Vui lòng đăng nhập để tiếp tuc',
    authentification_check_your_email:
        'Vui lòng kiểm tra email để hoàn thành đăng kí!',
    authentification_: '',

    header_home: 'Trang chủ',
    header_blog: 'Blog',
    header_user_profile: 'Hồ sơ cá nhân',
    header_edit_profile: 'Thay đổi hồ sơ cá nhân',
    header_best_answers: 'Câu trả lời tốt nhất',
    header_logout: 'Đăng xuất',
    home_ask_a_question: 'Đặt một câu hỏi',
    home_share_and_grow: 'Cùng chia sẻ và mở rộng tri thức!',
    home_description: `We want to connect the people who have knowledge to the people who need it, to bring
  together people with different perspectives so they can understand each other better,
  and to empower everyone to share their knowledge.`,
    home_create_a_new_account: 'Tạo tài khoản mới',

    nav_home: 'Trang chủ',
    nav_communities: 'Cộng đồng',
    nav_questions: 'Câu hỏi',
    nav_new_question: 'Câu hỏi mới',
    nav_trending_question: 'Câu hỏi nổi bật',
    nav_must_read_question: 'Câu hỏi cần phải đọc',
    nav_hot_question: 'Câu hỏi hot',
    nav_tags: 'Tags',
    nav_badges: 'Huy hiệu',
    nav_users: 'Người dùng',
    nav_help: 'Giúp đỡ',
    nav_ask_a_question: 'Đặt một câu hỏi',
    nav_best_answers: 'Câu trả lời hay',
    nav_top_members: 'Người dùng nổi bật',

    question_tell_us_your_questions: 'Hãy nói thêm về câu hỏi của bạn',
    question_your_description:
        'Mô tả của bạn giúp người đọc có đầy đủ thông tin để trả lời câu hỏi của bạn.',
    question_check_out_these_examples:
        'Hãy xem các ví dụ tuyệt vời về mô tả câu hỏi',
    question_want_more_help: 'Cần trợ giúp thêm',
    question_review_question: 'Xem lại câu hỏi',
    question_let_one_more_look: `Gần xong rồi! Hãy xem lại câu hỏi của bạn một lần nữa trước khi đăng. Đừng lo lắng, bạn có thể thay đổi nó sau khi đã đăng.`,
    question_check_for_typos: 'Kiểm tra lỗi chính tả, từ lóng.',
    question_for_exemple: 'Ví dụ',
    question_format_text: 'Tùy biến văn bản với',
    question_donnot_include_slang: ` Không nên viết tắt hay dùng từ lóng: “b ko thể vì nó là of m.“`,
    question_these_tips_for_editing: 'những gợi ý khi sử dụng Markdown',
    question_for_guidance: 'hướng dẫn',
    question_post_your_question: 'Đăng câu hỏi',
    question_what_your_programming: `Câu hỏi lập trình của bạn là gì? Bạn cần cụ thể nó.`,
    question_what_languages_technologies:
        'Framework trong câu hỏi của bạn là gì?',
    question_tags_help_the_right_people:
        'Gắn tags để giúp mọi người tìm thấy câu hỏi của bạn dễ dàng hơn.',
    question_identify_your_tags: `Tìm tags của bạn bằng cách hoàn thành câu hỏi: “Câu hỏi của mình là về…”`,
    question_include_tags_that:
        'Chỉ gán những tags liên quan đến câu hỏi của bạn, ví dụ như europe, us,...',
    question_only_included_in: 'chỉ bao gồm trong phạm vi đã đặt ra',
    question_your_title_help:
        'Tiêu đề của câu hỏi sẽ giúp người trả lời hiểu nhanh về vấn đề của bạn',
    question_imagine_you:
        'Tưởng tượng bạn đang hỏi một nhà phát triển phần mềm khác',
    question_is_there_an_R:
        'Có hay không một hàm trong R để tìm chỉ số của một phần tử trong một vector',
    question_please_help_with_R: 'Cần giúp đỡ với R language',
    quetion_what_is_your_title: 'Đặt tiêu đề cho câu hỏi của bạn',
    question_what_category_of_questions: 'Chọn lĩnh vực bạn muốn hỏi',
    question_we_will_help_you:
        'Chúng tôi sẽ tìm cho bạn câu trả lời phù hợp nhất',
    question_i_have_a_question_about: 'Tôi có một câu hỏi về học tập',
    question_i_need_help_with: 'Tôi cần giải quyết vấn đề về việc làm',
    question_i_nedd_to_troubleshoot: 'Tôi cần giải quyết vấn đề về định cư',
    question_answer_min_20: 'Vui lòng để lại câu trả lời ít 20 kí tự',
    question_search_question: 'Tìm kiếm câu hỏi',
    question_hit_enter_to_search: 'Nhấn enter để tìm kiếm',
    question_resolved: 'Đã được giải quyết',
    question_set_mode: 'Chế độ hiển thị của câu hỏi là gì?',
    question_set_mode_des:
        'Bạn có thể đặt chế độ hiển thị cho câu hỏi, nó có thể ở dạng riêng tư hoặc công khai. Nếu ở chế độ riêng tư, thì câu hỏi chỉ giới hạn bạn và những người dùng được chọn phía dưới. ',
    question_support_list:
        'Chọn người (nhiều nhất là 2) sẽ trả lời câu hỏi của bạn?',
    question_support_list_des:
        'Chúng tôi sẽ liên lạc đến họ để trả lời vấn đề của bạn. {{sub}}',
    question_support_list_des_sup_empty:
        'Bạn có thể để nó trống nếu như không biết sẽ gửi câu hỏi đến ai',
    question_support_list_require:
        'Bởi vì bạn chọn câu hỏi ở dang riêng tư, nên bạn phải chọn ít nhất 1 người để trả lời câu hỏi của bạn.',

    question_leaved_an_answer: 'Câu trả lời đã được thêm',
    question_approved_this_answer: 'Câu trả lời đã được chấp nhận',
    question_created_a_question: 'Đã tạo mới câu hỏi',

    answer_best_answers: 'Câu trả lời tốt nhất',
    answer_leave_answer: 'Để lại một câu trả lời',

    share_on_facebook: 'Chia sẻ lên Facebook',
    share_on_twitter: 'Chia sẻ lên Twitter',
    share_on_linkedIn: 'Chia sẻ lên LinkedIn',

    badges_point_system: 'Hệ thống tính điểm',
    badges_beside_gaining_reputation:
        'Bên cạnh nâng cao uy tín bằng việc đặt câu hỏi và trả lời, bạn có thể nhận được huy hiệu bằng cách giúp đỡ người khác (bình chọn cho câu hỏi hay, câu trả lời tốt v.v).',
    badges_shown: 'Huy hiệu sẽ xuất hiện trên trang của bạn.',
    badges_points_for_a_new: 'Điểm cho người dùng mới',
    badges_choosing_the_best: 'Chọn một câu trả lời tốt nhất cho một câu hỏi',
    badges_add_an_answer: 'Thêm một câu trả lời',
    badges_voting_a_question: 'Bình chọn cho một câu hỏi',
    badges_following_a_user: 'Theo dõi một người dùng khác trong cộng đồng',
    badges_voting_an_answer: 'Bình chọn cho một câu trả lời',
    badges_badges_system: 'Hệ thống tính điểm',
    badges_pundit: 'Học giả',
    badges_explainer: 'Người hướng dẫn',
    badges_professional: 'Professional',
    badges_enlightened: 'Người khai sáng',
    badges_you_must_have: 'Tổng điểm của bạn ít nhất là',
    badges_in_at_least: 'ít nhất',
    badges_non_community_wiki:
        'câu trả lời wiki ngoài cộng đồng để đạt được huy hiệu này. Câu trả lời cho điểm cao nhất vượt qua câu trả lời được chấp nhận với số điểm cao hơn',

    mainpage_recent_question: 'Câu hỏi gần đây',
    mainpage_most_answerd: 'Trả lời nhiều',
    mainpage_most_visited: 'Xem nhiều',
    mainpage_most_voted: 'Vote nhiều nhất',
    mainpage_no_answers: 'Không có câu trả lời',
    mainpage_danang_vietnam: 'Đà Nẵng, Việt Nam',
    mainpage_load_more_questions: 'Xem thêm câu trả lời',

    login_thank_to_login_to_continue: 'Vui lòng đăng nhập để tiếp tục',

    contact_us_hello: 'VCNC chúc bạn một ngày tốt lành!',
    contact_us_if_you_want_to_share:
        'Nếu bạn muốn chia sẻ câu chuyện của mình trên VCNC blog, vui lòng để lại lời nhắn cho VCNC tại ',
    contact_us_reply_soon:
        ' Chúng tôi sẽ liên hệ bạn trong thời gian sớm nhất.',
    contact_us_feedback: 'Mọi ý kiến phản hồi khác vui lòng gửi đến :',
    contact_us_sincerely: 'Chân thành cảm ơn đóng góp của bạn!',

    about_us_VCNC: 'Vietnamese Counselling and Connecting',
    about_us_sologan: 'Get people connected',
    about_us_our_story: 'Câu chuyện của chúng tôi',
    about_us_story: `Team sáng lập của VCNC gồm những cựu học sinh của THPT chuyên Lê Quý Đôn, Đà Nẵng đang học tập và làm việc ở nước ngoài. Khi đặt chân đến một đất nước xa lạ, chúng tôi nhận ra sự cần thiết của việc tập hợp người Việt Nam lại với nhau để giúp đỡ nhau đi lên. Đó là lý do chúng tôi tạo ra một nền tảng nơi mọi người có thể nhận được những lời khuyên và hỗ trợ từ những người có kinh nghiệm cho sự nghiệp của mình.`,
    about_us_our_mission: 'Mục tiêu',
    about_us_mission:
        'Chúng tôi hướng đến tham vọng xây dựng một cộng đồng lớn nhất và ‘ngầu’ nhất Việt Nam nơi mọi thành viên nhận được sự hỗ trợ tốt nhất trên con đường sự nghiệp.',
    about_us_what_we_do: 'Cụ thể, chúng tôi làm gì?',
    about_us_do:
        'Chúng tôi xây dựng một trang web để mọi người đặt câu hỏi và nhận được những câu trả lời đáng tin cậy từ người có kinh nghiệm ở khắp nơi trên thế giới thông qua các thuật toán cấp cao. Bên cạnh đó, chúng tôi đưa ra những gói dịch vụ tư vấn kết nối bạn trực tiếp với một chuyên gia trong ngành. Hệ thống của chúng tôi sẽ giúp bạn nhận được những hỗ trợ cũng như những mối quan hệ bạn cần trong sự nghiệp của bạn.',
    about_us_our_team: 'Các thành viên',

    forgot_password_please_verify_your_email:
        'Vui lòng kiểm tra email của bạn để tạo lại mật khẩu mới',
    authentification_enter_new_password: 'Vui lòng nhập mật khẩu mới',
    authentification_new_password: 'Mật khẩu mới',
    authentification_confirm_new_password: 'Xác nhận mật khẩu mới',
    authentification_invalid_comfirm_password: 'Xác nhận mật khẩu không khớp',
    authentification_your_password_has_been_reset:
        'Mật khẩu của bạn đã được đặt lại',
    authentication_please_enter_email_and_password:
        'Vui lòng nhập email và mật khẩu để tiếp tục',

    form_require_all_values: 'Vui lòng nhập đầy đủ thông tin.',
    form_your_job: 'Công việc của bạn',
    form_current_role: 'Công việc hiện tại của tôi',
    form_ex_work_manager: 'Ví dụ: Quản lý',
    form_your_school: 'Trường của bạn',

    my_profile_you_come_from: 'Bạn đến từ',
    my_profile_choose_one_country: 'Chọn một nước',
    my_profile_user_info_updated: 'Hồ sơ của bạn đã được thay đổi',
    my_profile_change_password: 'Thay đổi mật khẩu',
    my_profile_old_password: 'Mật khẩu hiện tại',
    my_profile_new_password: 'Mật khẩu mới',
    my_profile_passwords_not_identique: 'Mật khẩu mới không đồng nhất',
    my_profile_change_password_success: 'Bạn đã thay đổi mật khẩu thành công!',
    my_profile_confirm_new_password: 'Xác nhận mật khẩu mới',
    my_profile_please_complete_all_fields: 'Vui lòng điền đầy đủ thông tin',
    my_profile_passwords_contrain:
        'Mật khẩu phải chứa ít nhất 8 kí tự, 1 chữ hoa, 1 chữ thường và 1 số',

    user_info_question_asked: 'Câu hỏi đã hỏi',
    user_info_amswers_related: 'Những câu trả lời',
    user_info_added_an_answer: 'Được trả lời vào ngày',
    user_info_experience_created: 'Kinh nghiệm đã được thêm!',
    user_info_experience_updated: 'Kinh nghiệm đã được chỉnh sửa!',
    user_info_education_created: 'Giáo dục đã được thêm!',
    user_info_education_updated: 'Giáo dục đã chỉnh sửa!',

    home_ask_verified_professionals:
        'Xin lời khuyên về định hướng nghề nghiệp, kinh nghiệm phỏng vấn, thông tin về công ty từ các chuyên gia từ các công ty lớn hàng đầu...',
    home_want_to_get:
        'Bạn muốn thêm thu nhập từ việc đưa ra lời khuyên/ý kiến?',
    home_find_out_how: 'Gia nhập VCNC',

    workspace_if_you_are_asking: 'Nếu bạn là người đặt câu hỏi',
    workspace_post_a_question: 'Đặt một câu hỏi',
    workspace_choose_professionals:
        'Chọn người trả lời câu hỏi bạn muốn được kết nối tới',
    workspace_receive_answer_from: 'Nhận được câu trả lời bạn cần',
    workspace_rate_your_experience:
        'Đánh giá câu trả lời và nhận được điểm thưởng vào tài khoản',
    workspace_if_you_are_answering: 'Nếu bạn là người trả lời',
    workspace_get_notification:
        'Nhận thông báo từ VCNC nếu bạn được ai đó yêu cầu trả lời một câu hỏi',
    workspace_answer_the_assigned: 'Trả lời câu hỏi nhận được trong vòng 24h',
    workspace_get_paid: 'Nhận điểm thưởng sau khi đăng tải câu trả lời',
    workspace_our_support: 'Hỗ trợ',
    workspace_give_instruction_to_ask: 'Giới thiệu những mẫu câu hỏi',
    workspace_give_rule_to_answer: 'Đưa ra các yêu cầu về nội dung cần trả lời',
    workspace_censorship_content:
        'Kiểm duyệt nội dung (câu hỏi và câu trả lời)',

    footer_all_right_reserved: 'All rights reserved © 2020',

    answer_added_an_answer_on: 'Trả lời vào ngày',

    infos_what_does_VCNC_do: 'VCNC làm gì?',
    infos_what_does_VCNC_do_description:
        'Chúng tôi giúp kết nối bạn với cộng đồng những người có kinh nghiệm từ khắp nơi trên thế giới để giúp bạn tìm được câu trả lời tốt nhất cho vấn đề bạn gặp phải, cũng như những hỗ trợ bạn cần cho sự nghiệp của bạn.',
    infos_get_started: 'Nhưng làm thế nào để bắt đầu? Cực đơn giản!',
    infos_new_step1:
        'Đăng ký một tài khoản với VCNC. Bạn có thể đăng ký bằng email hoặc đơn giản là kết nối trực tiếp với tài khoản google/facebook sẵn có của bạn.',
    infos_new_step2:
        'Giờ bạn đã sẵn sàng. Truy cập vào vcnc.app và đặt ngay một câu hỏi nào để kết nối với cộng đồng professionals của VCNC nào!',
    infos_new_step3:
        'Đừng quên quay trở lại sau vài ngày để xem câu trả lời cho yêu cầu của bạn. Bạn sẽ nhận được thông báo ngay khi có ai đó vào trả lời. Nếu bạn hài lòng với một câu trả lời nào đó, đừng quên nhấn HÀI LÒNG với câu trả lời đó. Người bạn đã đưa ra câu trả lời sẽ rất biết ơn bạn đấy!',
    infos_conclusion: 'Cuối cùng, chúng tôi rất vui khi có bạn ở đây!'
};
