export default {
  common_questions: 'Câu hỏi',
  common_answer: 'Câu trả lời',
  common_answers: 'Câu trả lời',
  common_stats: 'Số liệu',
  common_users: 'Người dùng',
  common_popular: 'Độ phổ biến',
  common_slidebar: 'Thanh trượt',
  common_points: 'Điểm',
  common_previous_step: 'Quay lại',
  common_next: 'Tiếp theo',
  common_bold: 'đậm',
  common_and: 'và',
  common_italic: 'nghiêng',
  common_check_out: 'Thanh toán',
  common_title: 'Tiêu đề',
  common_tags: 'Tags',
  common_for_exemple: 'Ví dụ',
  common_voted: 'Thích',
  common_oldest: 'Cũ nhất',
  common_rencent: 'Mới nhất',
  common_view_profile: 'Xem trang cá nhân',
  common_approve: 'Đồng ý',
  common_reply: 'Trả lời',
  common_share: 'Chia sẻ',
  common_report: 'Báo cáo',
  common_home: 'Trang chủ',
  common_asked: 'Đã hỏi',
  common_in: 'Trong',
  common_language: 'Ngôn ngữ',
  common_views: 'Lượt xem',
  common_followers: 'Lượt theo dõi',
  common_name: 'Tên',
  common_badges: 'Huy hiệu',
  common_beginner: 'Người bắt đầu',
  common_teacher: 'Người hướng dẫn',
  common_top_members: 'Thành viên tích cực',
  common_login:'Đăng nhập',
  common_registre:'Đăng ký',
  common_forgot_password: 'Quên mật khẩu',
  common_email: 'Email',
  common_password: 'Mật khẩu',

  authentification_enter_your_email: 'Nhập địa chỉ email của bạn',
  authentification_reset_password: 'Đặt lại mật khẩu',
  authentification_back_to_login: 'Trở về đăng nhập',
  authentification_first_name: 'Tên',
  authentification_last_name: 'Họ',
  authentification_confirm_password: 'Xác nhận mật khẩu',
  authentification_create_account: 'Tạo tài khoản',
  authentification_remember_me: 'Nhớ thông tin đăng nhập',
  authentification_sign_up: 'Đăng ký',
  authentification_forgot_your_password: 'Quên mật khẩu',
  authentification_donot_have_account: `Bạn chưa có tài khoản`,
  authentification_this_page_need_to_authenticate: 'Vui lòng đăng nhập để tiếp tuc',
  authentification_: '',

  header_home: 'Trang chủ',
  header_about_us: 'Giới thiệu',
  header_contact_us: 'Liên hệ',
  header_blog: 'Blog',
  header_user_profile: 'Hồ sơ cá nhân',
  header_edit_profile: 'Thay đổi hồ sơ cá nhân',
  header_best_answers: 'Câu trả lời tốt nhất',
  header_logout: 'Đăng xuất',
  home_ask_a_question: 'Đặt một câu hỏi',
  home_share_and_grow: "Cùng chia sẻ và mở rộng tri thức!",
  home_description: `We want to connect the people who have knowledge to the people who need it, to bring
  together people with different perspectives so they can understand each other better,
  and to empower everyone to share their knowledge.`,
  home_create_a_new_account: 'Tạo tài khoản mới',
  
  nav_home: 'Trang chủ',
  nav_communities: 'Cộng đồng',
  nav_questions: 'Câu hỏi',
  nav_new_question: 'Câu hỏi mới',
  nav_trending_question: 'Câu hỏi nổi bật',
  nav_must_read_question: 'Câu hỏi cần phải đọc',
  nav_hot_question: 'Câu hỏi hot',
  nav_tags: 'Tags',
  nav_badges: 'Huy hiệu',
  nav_users: 'Người dùng',
  nav_help: 'Giúp đỡ',
  nav_ask_a_question: 'Đặt một câu hỏi',
  nav_best_answers: 'Câu trả lời tốt nhất',
  nav_top_members: 'Người dùng nổi bật',
  
  question_tell_us_your_questions: 'Hãy nói thêm về câu hỏi của bạn',
  question_your_description:
    'Mô tả của bạn giúp người đọc có đầy đủ thông tin để trả lời câu hỏi của bạn.',
  question_check_out_these_examples:
    'Hãy xem các ví dụ tuyệt vời về mô tả câu hỏi',
  question_want_more_help: 'Cần trợ giúp thêm',
  question_review_question: 'Xem lại câu hỏi',
  question_let_one_more_look: `Gần xong rồi! Hãy xem lại câu hỏi của bạn một lần nữa trước khi đăng. Đừng lo lắng, bạn có thể thay đổi nó sau khi đã đăng.`,
  question_check_for_typos:
    'Kiểm tra lỗi chính tả, từ lóng.',
  question_for_exemple: 'Ví dụ',
  question_format_text: 'Tùy biến văn bản với',
  question_donnot_include_slang: ` Không nên viết tắt hay dùng từ lóng: “b ko thể vì nó là of m.“`,
  question_these_tips_for_editing: 'những gợi ý khi sử dụng Markdown',
  question_for_guidance: 'hướng dẫn',
  question_post_your_question: 'Đăng câu hỏi',
  question_what_your_programming: `Câu hỏi lập trình của bạn là gì? Bạn cần cụ thể nó.`,
  question_what_languages_technologies:
    'Ngôn ngữ, công nghệ, framework trong câu hỏi của bạn là gì?',
  question_tags_help_the_right_people:
    'Gắn tags để giúp mọi người tìm thấy câu hỏi của bạn dễ dàng hơn.',
  question_identify_your_tags: `Tìm tags của bạn bằng cách hoàn thành câu hỏi: “Câu hỏi của mình là về…”`,
  question_include_tags_that:
    'Chỉ gán những tags liên quan đến câu hỏi của bạn, ví dụ như europe, us,...',
  question_only_included_in: 'chỉ bao gồm trong phạm vi đã đặt ra',
  question_your_title_help:
  'Tiêu đề của câu hỏi sẽ giúp người trả lời hiểu nhanh về vấn đề của bạn',
  question_imagine_you: 'Tưởng tượng bạn đang hỏi một nhà phát triển phần mềm khác', 
  question_is_there_an_R: 'Có hay không một hàm trong R để tìm chỉ số của một phần tử trong một vector',
  question_please_help_with_R: 'Cần giúp đỡ với R language',
  quetion_what_is_your_title: 'Đặt tiêu đề cho câu hỏi của bạn',
  question_what_category_of_questions:
    'Chọn lĩnh vực bạn muốn hỏi',
  question_we_will_help_you: "Chúng tôi sẽ tìm cho bạn câu trả lời phù hợp nhất",
  question_i_have_a_question_about: 'Tôi có một câu hỏi về học tập',
  question_i_need_help_with: 'Tôi cần giải quyết vấn đề về việc làm',
  question_i_nedd_to_troubleshoot: 'Tôi cần giải quyết vấn đề về định cư',
  
  answer_best_answers: 'Câu trả lời tốt nhất',
  answer_leave_answer: 'Để lại một câu trả lời',
  
  share_on_facebook: 'Chia sẻ lên Facebook',
  share_on_twitter: 'Chia sẻ lên Twitter',
  share_on_linkedIn: 'Chia sẻ lên LinkedIn',
  
  badges_point_system: 'Hệ thống tính điểm',
  badges_beside_gaining_reputation: 'Bên cạnh nâng cao uy tín bằng việc đặt câu hỏi và trả lời, bạn có thể nhận được huy hiệu bằng cách giúp đỡ người khác (bình chọn cho câu hỏi hay, câu trả lời tốt v.v). Huy hiệu sẽ xuất hiện trên trang của bạn',
  badges_points_for_a_new: 'Điểm cho người dùng mới',
  badges_choosing_the_best: 'Chọn một câu trả lời tốt nhất cho một câu hỏi',
  badges_add_an_answer: 'Thêm một câu trả lời',
  badges_voting_a_question: 'Bình chọn cho một câu hỏi',
  badges_following_a_user: 'Theo dõi một người dùng khác trong cộng đồng',
  badges_voting_an_answer: 'Bình chọn cho một câu trả lời',
  badges_badges_system: 'Hệ thống tính điểm',
  badges_pundit: 'Học giả',
  badges_explainer: 'Người hướng dẫn',
  badges_professional: 'Professional',
  badges_enlightened: 'Người khai sáng',
  badges_you_must_have: 'Tổng điểm của bạn ít nhất là',
  badges_in_at_least: 'ít nhất',
  badges_non_community_wiki: 'câu trả lời wiki ngoài cộng đồng để đạt được huy hiệu này. Câu trả lời cho điểm cao nhất vượt qua câu trả lời được chấp nhận với số điểm cao hơn',

  mainpage_recent_question : 'Câu hỏi gần đây',
  mainpage_most_answerd: 'Trả lời nhiều nhất',
  mainpage_most_visited:'Xem nhiều nhất',
  mainpage_most_voted: 'Vote nhiều nhất',
  mainpage_no_answers: 'Không có câu trả lời',
  mainpage_danang_vietnam : 'Đà Nẵng, Việt Nam',
  mainpage_load_more_questions: 'Xem thêm câu trả lời',

  login_thank_to_login_to_continue: 'Vui lòng đăng nhập để tiếp tục'
 };
 